// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwu3FzX2kL4H_PK1lXoxvDPrPel9s-nHc',
    appId: '1:881138100497:web:da4e2780f226671ab884b0',
    messagingSenderId: '881138100497',
    projectId: 'zupzup-951d3',
    authDomain: 'zupzup-951d3.firebaseapp.com',
    databaseURL: 'https://zupzup-951d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zupzup-951d3.appspot.com',
    measurementId: 'G-KHH8FS0TQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRFZEZ43PoRTrfLBrEOBmjfsZRj2pyIEo',
    appId: '1:881138100497:android:03d613ddf23d58c2b884b0',
    messagingSenderId: '881138100497',
    projectId: 'zupzup-951d3',
    databaseURL: 'https://zupzup-951d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zupzup-951d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeUfGQ46R4qE_RlpxMdmehbThaBwryK10',
    appId: '1:881138100497:ios:6f4b184917e6a7b2b884b0',
    messagingSenderId: '881138100497',
    projectId: 'zupzup-951d3',
    databaseURL: 'https://zupzup-951d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zupzup-951d3.appspot.com',
    iosClientId: '881138100497-t08p7g9b59gm1cffc8lqmb13cl6krvig.apps.googleusercontent.com',
    iosBundleId: 'com.example.jupjup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeUfGQ46R4qE_RlpxMdmehbThaBwryK10',
    appId: '1:881138100497:ios:6f4b184917e6a7b2b884b0',
    messagingSenderId: '881138100497',
    projectId: 'zupzup-951d3',
    databaseURL: 'https://zupzup-951d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zupzup-951d3.appspot.com',
    iosClientId: '881138100497-t08p7g9b59gm1cffc8lqmb13cl6krvig.apps.googleusercontent.com',
    iosBundleId: 'com.example.jupjup',
  );
}
